#!/usr/bin/env python3
"""Generate plugs/plug_uTimerScript.moos -- the handling block.

The maneuver sequence from control_refactor_plan.md section 8.3,
as a uTimerScript that drives pBBPID directly:

    warmup     base heading @ 0.8 m/s, 15 s
    steps A    +30 / -60 / +120 deg @ slow speed, 25 s holds
    steps B    +30 / -60 / +120 deg @ fast speed, 25 s holds
    zigzag     +/-20 deg about base, 8 s flips x6 @ 1.0 m/s
    pivot      speed 0, +/-170 held 20 s, twice (baseline-comparable)
    pivot180   speed 0, TRUE +180 turns (tests the ff_step_limit
               guard; --pivot180 0 to skip on a legacy config)
    straight   base heading @ fast speed, 60 s
    speed      staircase on base heading (speed-loop evidence:
               t63, standing error, FF-vs-integral thrust share)
    done       speed 0

Design points, both deliberate:

  * Setpoints are RE-POSTED EVERY SECOND. pBBPID treats a quiet
    commander as stale (1.5 s) and stops -- that safety gate stays
    live, and when the script pauses the boat therefore stops
    being commanded, which is exactly right.

  * The script's `condition` holds it to BB_CMD_AUTHORITY=AUTONOMY
    (bridged from the front seat). Elapsed time freezes while the
    condition is unmet, so an RC takeover pauses the block and a
    return to AUTO resumes it mid-sequence.

Headings are absolute, baked at generation time (nsplug cannot do
arithmetic). Regenerate to change the base:

    ./gen_maneuver.py --base 150
"""

import argparse
import os

def wrap(h):
    return h % 360.0

def write_rc_cal(out):
    """Session-0 script: present, inert, and inert for two reasons.

    The calibration run is flown entirely on RC (playbook section 4), so
    nothing may command the boat under autonomy. `paused = true` stops
    the script clock, and there are no events to fire if it were ever
    unpaused -- belt and braces, because a bumped CH6 on a boat that is
    mid-pivot at zero surge is exactly the situation this run puts the
    operator in repeatedly.

    The mission is otherwise unchanged, so pLogger, the front-seat
    bridge, and the variable set are bit-identical to a block run and
    analysis/rc_cal.py reads the same back-seat alog.
    """
    lines = [
        "//------------------------------------------------------------",
        "// GENERATED by gen_maneuver.py --rc-cal -- do not edit by hand.",
        "//",
        "// SESSION-0 OPEN-LOOP CALIBRATION: this script is INERT.",
        "// The boat is flown on RC for the whole run; see the run card in",
        "// missions/handling_block/README.md and score with",
        "// analysis/rc_cal.py.",
        "//------------------------------------------------------------",
        "",
        "ProcessConfig = uTimerScript",
        "{",
        "  AppTick   = 4",
        "  CommsTick = 4",
        "",
        "  script_name = RC_CAL_INERT",
        "  paused      = true",
        "  shuffle     = false",
        "  reset_max   = 0",
        "",
        "  // No events. Nothing to fire even if something unpauses this.",
        "}",
    ]
    outdir = os.path.dirname(out)
    if outdir:
        os.makedirs(outdir, exist_ok=True)
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {out}: RC-CAL INERT script (paused, 0 events, 0s autonomy)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", type=float, default=150.0,
                    help="base heading, deg (default 150)")
    ap.add_argument("--slow", type=float, default=0.5)
    ap.add_argument("--fast", type=float, default=1.5)
    ap.add_argument("--hold", type=float, default=25.0,
                    help="step hold time, s")
    ap.add_argument("--pivot180", type=int, default=2,
                    help="number of TRUE 180-deg pivots appended after the "
                         "+/-170 baseline pair; requires pBBPID's "
                         "ff_step_limit guard (0 to skip on legacy config)")
    ap.add_argument("--speed-steps", default="0.5,1.0,1.5,0.8",
                    help="speed staircase on the base heading, m/s "
                         "(comma-separated; empty string to skip)")
    ap.add_argument("--speed-hold", type=float, default=15.0,
                    help="hold per speed step, s")
    ap.add_argument("--rc-cal", action="store_true",
                    help="session-0 open-loop calibration: emit an INERT "
                         "script (paused, zero events) so the mission logs "
                         "and bridges exactly as usual while the operator "
                         "flies the boat on RC. Nothing can command the "
                         "boat under autonomy, even if CH6 is bumped.")
    ap.add_argument("--out", default="plugs/plug_uTimerScript.moos")
    args = ap.parse_args()

    if args.rc_cal:
        write_rc_cal(args.out)
        return

    B = args.base
    phases = []   # (name, hdg, spd, dur)

    # Warmup on base heading.
    phases.append(("warmup", wrap(B), 0.8, 15))

    # Step blocks: step sizes +30, -60, +120 from wherever the
    # previous phase ended, signs alternating to stay in the box.
    h = B
    for spd, tag in ((args.slow, "stepA"), (args.fast, "stepB")):
        for step in (30, -60, 120):
            h = wrap(h + step)
            phases.append((f"{tag}_{step:+d}", h, spd, args.hold))

    # Zigzag about base.
    for i in range(6):
        z = wrap(B + (20 if i % 2 == 0 else -20))
        phases.append((f"zig_{i+1}", z, 1.0, 8))

    # Pivots: speed 0, two 170-deg turns. Kept at 170 (not 180) for
    # comparability with the 27 Aug baseline: an exact half-turn is
    # degenerate for the LEGACY feedforward (cross-product sign at
    # the +/-180 boundary is numeric noise) -- on the first block run
    # the FF picked the wrong sign and cancelled the railed feedback,
    # pivoting the boat at 2 deg/s instead of 25.
    h = wrap(B - 20)             # where the zigzag ended
    for i in range(2):
        h = wrap(h + 170)
        phases.append((f"pivot_{i+1}", h, 0.0, 20))

    # TRUE 180-deg pivots: the case the ff_step_limit guard exists
    # for (steps beyond the limit publish no FF, so the sign-noise
    # hazard is gone and feedback rails the turn). Appended after
    # the baseline pair so both configurations are measured in one
    # run; alternate direction to end near the entry heading.
    for i in range(args.pivot180):
        h = wrap(h + 180)
        phases.append((f"pivot180_{i+1}", h, 0.0, 20))

    # Straight run on base.
    phases.append(("straight", wrap(B), args.fast, 60))

    # Speed staircase on the base heading: the speed loop's own
    # step-response block (heading held constant so yaw coupling is
    # minimal). Feeds the scorer's speed t63 / standing-error /
    # FF-share columns -- the evidence for speed_pid and ff_speed.
    speeds = [float(x) for x in args.speed_steps.split(",") if x.strip()]
    for i, spd in enumerate(speeds):
        phases.append((f"speed_{i+1}", wrap(B), spd, args.speed_hold))

    phases.append(("done", wrap(B), 0.0, 10))

    total = sum(p[3] for p in phases)

    lines = []
    lines.append("//------------------------------------------------------------")
    lines.append("// GENERATED by gen_maneuver.py -- do not edit by hand.")
    lines.append(f"//   base={B:.0f}  slow={args.slow}  fast={args.fast}"
                 f"  hold={args.hold}  pivot180={args.pivot180}"
                 f"  speed_steps={args.speed_steps}  total={total:.0f}s")
    lines.append("//------------------------------------------------------------")
    lines.append("")
    lines.append("ProcessConfig = uTimerScript")
    lines.append("{")
    lines.append("  AppTick   = 4")
    lines.append("  CommsTick = 4")
    lines.append("")
    lines.append("  script_name = HANDLING_BLOCK")
    lines.append("  paused      = false")
    lines.append("  shuffle     = false")
    lines.append("  reset_max   = 0")
    lines.append("")
    lines.append("  // Advance while autonomy HAS the boat, or is being OFFERED it.")
    lines.append("  // The second clause breaks the bootstrap deadlock: pBBPID is")
    lines.append("  // not valid until this script posts DESIRED_*, and the arbiter")
    lines.append("  // does not select AUTONOMY until pBBPID is valid -- but while")
    lines.append("  // CH6 is in AUTO with nothing commanding, the arbiter says")
    lines.append("  // exactly stop=AUTONOMY_INVALID, which is the offer. An RC")
    lines.append("  // takeover (authority=RC, stop=NONE) freezes the clock;")
    lines.append("  // ALL_STOP and a quiet pBBPID pause the block too.")
    lines.append("  //")
    lines.append("  // EXACTLY TWO parenthesized clauses: lib_logic rejects a flat")
    lines.append("  // three-way 'or' (the right side of the first 'or' must itself")
    lines.append("  // be globally parenthesized) -- and uTimerScript then runs")
    lines.append("  // UNCONDITIONED on the bad line. Seen 2026-08-27.")
    lines.append("  condition   = (BB_CMD_AUTHORITY = AUTONOMY) or "
                 "(BB_CMD_STOP_REASON = AUTONOMY_INVALID)")
    lines.append("")
    lines.append("  // Settle time after autonomy first gets the boat.")
    lines.append("  delay_start = 5")
    lines.append("")

    t = 0.0
    for name, hdg, spd, dur in phases:
        lines.append(f"  // ---- {name}: hdg {hdg:.0f}, spd {spd}, {dur:.0f}s ----")
        lines.append(f'  event = var=MANEUVER_PHASE, '
                     f'val="phase={name},hdg={hdg:.1f},spd={spd},dur={dur:.0f}", '
                     f'time={t:.0f}')
        # Re-post the setpoints every second through the phase.
        s = 0.0
        while s < dur:
            lines.append(f"  event = var=DESIRED_HEADING, val={hdg:.1f}, time={t+s:.0f}")
            lines.append(f"  event = var=DESIRED_SPEED,  val={spd}, time={t+s:.0f}")
            s += 1.0
        t += dur
        lines.append("")

    lines.append("}")

    outdir = os.path.dirname(args.out)
    if outdir:
        os.makedirs(outdir, exist_ok=True)
    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {args.out}: {len(phases)} phases, {total:.0f}s of autonomy time")

if __name__ == "__main__":
    main()
