#!/usr/bin/env python3
"""
Navigator Gyro Bias Calibration Script

Reads a CSV from sample_navigator (--gyro-cal mode) and computes gyro bias.
Validates that the vehicle was stationary during the capture.

Usage:
    python3 get_nav_gyro_cal.py gyro_cal_*.csv
    python3 get_nav_gyro_cal.py gyro_cal_*.csv -o ~/system_data/zoe-bb/nav/

Output:
    gyro_bias.dat in current directory (or -o path)
"""

import argparse
import sys
from pathlib import Path
import numpy as np
import pandas as pd


def main():
    parser = argparse.ArgumentParser(description='Navigator Gyro Bias Calibration')
    parser.add_argument('csv_file', help='CSV from sample_navigator --gyro-cal')
    parser.add_argument('--output', '-o', help='Output directory (default: current directory)')
    parser.add_argument('--gyro-threshold', type=float, default=5.0,
                        help='Max gyro rate (deg/s) to consider stationary (default: 5.0)')
    parser.add_argument('--verbose', '-v', action='store_true')
    args = parser.parse_args()

    csv_path = Path(args.csv_file)
    if not csv_path.exists():
        print(f"Error: {csv_path} not found")
        sys.exit(1)

    df = pd.read_csv(csv_path)
    df.columns = df.columns.str.strip()

    gyro_cols = ['nav_gyro_x_rads', 'nav_gyro_y_rads', 'nav_gyro_z_rads']
    accel_cols = ['nav_accel_x_ms2', 'nav_accel_y_ms2', 'nav_accel_z_ms2']

    for col in gyro_cols:
        if col not in df.columns:
            print(f"Error: column '{col}' not found in CSV")
            print(f"Available: {list(df.columns)}")
            sys.exit(1)

    gyro = df[gyro_cols].to_numpy()
    n = len(df)
    ts = df['timestamp_s'].to_numpy()
    dur = ts[-1] - ts[0]

    # Stationarity check: gyro rate magnitude
    gyro_mag_dps = np.linalg.norm(gyro, axis=1) * 180.0 / np.pi
    max_gyro_dps = np.max(gyro_mag_dps)
    mean_gyro_dps = np.mean(gyro_mag_dps)
    pct_above = np.sum(gyro_mag_dps > args.gyro_threshold) / n * 100

    gyro_mean = np.mean(gyro, axis=0)
    gyro_std = np.std(gyro, axis=0)

    # Accel stats (informational)
    has_accel = all(c in df.columns for c in accel_cols)
    accel_std = np.std(df[accel_cols].to_numpy(), axis=0) if has_accel else np.zeros(3)
    accel_mean_mag = np.mean(np.linalg.norm(df[accel_cols].to_numpy(), axis=0)) if has_accel else 0

    print(f"Navigator Gyro Bias Calibration")
    print(f"  Source: {csv_path.name}")
    print(f"  Samples: {n}, Duration: {dur:.1f}s")
    print(f"  Gyro bias (rad/s): [{gyro_mean[0]:.6f}, {gyro_mean[1]:.6f}, {gyro_mean[2]:.6f}]")
    print(f"  Gyro bias (deg/s): [{gyro_mean[0]*180/np.pi:.4f}, {gyro_mean[1]*180/np.pi:.4f}, {gyro_mean[2]*180/np.pi:.4f}]")
    print(f"  Gyro std  (rad/s): [{gyro_std[0]:.6f}, {gyro_std[1]:.6f}, {gyro_std[2]:.6f}]")
    print(f"  Max gyro rate: {max_gyro_dps:.2f} deg/s")
    print(f"  Mean gyro rate: {mean_gyro_dps:.2f} deg/s")
    if has_accel:
        print(f"  Accel std (m/s²): [{accel_std[0]:.4f}, {accel_std[1]:.4f}, {accel_std[2]:.4f}]")

    warnings = []
    if pct_above > 5:
        warnings.append(f"{pct_above:.1f}% of samples exceed {args.gyro_threshold} deg/s — vehicle may not have been stationary")
    if max_gyro_dps > args.gyro_threshold * 3:
        warnings.append(f"Max gyro rate {max_gyro_dps:.1f} deg/s is very high — check data")

    if warnings:
        print("\nWarnings:")
        for w in warnings:
            print(f"  {w}")

    # Output
    output_dir = Path(args.output) if args.output else Path('.')
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / 'gyro_bias.dat'

    with open(output_path, 'w') as f:
        f.write("# Gyro Bias Calibration (Navigator)\n")
        f.write("# Generated by get_nav_gyro_cal.py\n")
        f.write(f"# Source: {csv_path.name}\n")
        f.write(f"# Samples: {n}\n")
        f.write(f"# Duration: {dur:.1f}s\n")
        f.write(f"# Gyro bias (deg/s): [{gyro_mean[0]*180/np.pi:.4f}, {gyro_mean[1]*180/np.pi:.4f}, {gyro_mean[2]*180/np.pi:.4f}]\n")
        f.write(f"# Gyro std (rad/s): [{gyro_std[0]:.6f}, {gyro_std[1]:.6f}, {gyro_std[2]:.6f}]\n")
        f.write(f"# Max gyro rate: {max_gyro_dps:.2f} deg/s\n")
        if has_accel:
            f.write(f"# Accel std (m/s²): [{accel_std[0]:.4f}, {accel_std[1]:.4f}, {accel_std[2]:.4f}]\n")
        if warnings:
            for w in warnings:
                f.write(f"# WARNING: {w}\n")
        f.write(f"\nbias_x = {gyro_mean[0]:.12f}\n")
        f.write(f"bias_y = {gyro_mean[1]:.12f}\n")
        f.write(f"bias_z = {gyro_mean[2]:.12f}\n")

    print(f"\nSaved: {output_path}")


if __name__ == '__main__':
    main()
