#!/usr/bin/env python3
"""
Navigator Magnetometer Calibration Script

Levenberg-Marquardt ellipsoid fit for hard/soft iron calibration.
Simplified from moos-ivp-seascout/scripts/get_mag_cal_v3.py — Navigator only, LM only.

Usage:
    python3 get_nav_mag_cal.py nav_sample_*.csv
    python3 get_nav_mag_cal.py nav_sample_*.csv -o ~/system_data/zoe-bb/nav/

Output (current directory or -o path):
    mag_cal_nav.dat             Calibration parameters
    mag_cal_nav_diagnostics.png 3-panel diagnostic plot
"""

import argparse
import sys
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import least_squares


# ---------------------------------------------------------------------------
# Calibration
# ---------------------------------------------------------------------------
def _lse_init(data, ef, n_iter=3):
    """Quick LSE ellipsoid fit for LM initialization."""
    X = data.copy()
    cum_hi = np.zeros(3)
    for _ in range(n_iter):
        n = X.shape[0]
        D = np.column_stack([
            X[:,0]**2, X[:,1]**2, X[:,2]**2,
            2*X[:,0]*X[:,1], 2*X[:,0]*X[:,2], 2*X[:,1]*X[:,2],
            2*X[:,0], 2*X[:,1], 2*X[:,2],
        ])
        v = np.linalg.lstsq(D, np.ones(n), rcond=None)[0]
        A_q = np.array([[v[0],v[3],v[4]],[v[3],v[1],v[5]],[v[4],v[5],v[2]]])
        b_v = np.array([v[6],v[7],v[8]])
        try:
            center = -0.5 * np.linalg.solve(A_q, b_v)
        except np.linalg.LinAlgError:
            center = -0.5 * np.linalg.pinv(A_q) @ b_v
        cum_hi += center
        X = X - center

    hi = cum_hi
    Xc = data - hi
    n = len(Xc)
    D_M = np.column_stack([
        Xc[:,0]**2, Xc[:,1]**2, Xc[:,2]**2,
        2*Xc[:,0]*Xc[:,1], 2*Xc[:,0]*Xc[:,2], 2*Xc[:,1]*Xc[:,2],
    ])
    mp = np.linalg.lstsq(D_M, np.full(n, ef**2), rcond=None)[0]
    M = np.array([[mp[0],mp[3],mp[4]],[mp[3],mp[1],mp[5]],[mp[4],mp[5],mp[2]]])
    try:
        ev = np.linalg.eigvals(M)
        if np.min(ev) <= 0:
            M += (1e-6 - np.min(ev) + 1e-6) * np.eye(3)
        si = np.linalg.cholesky(M).T
    except np.linalg.LinAlgError:
        ev, evec = np.linalg.eigh(M)
        si = evec @ np.diag(np.sqrt(np.maximum(ev, 1e-6)))
    return hi, si


def calibrate_lm(mag_data, expected_field, max_iter=100):
    """Levenberg-Marquardt magnetometer calibration."""
    def residuals(params, data, target):
        hi = params[:3]
        sp = params[3:9]
        A = np.array([[sp[0],sp[3],sp[4]],[sp[3],sp[1],sp[5]],[sp[4],sp[5],sp[2]]])
        return np.linalg.norm((A @ (data - hi).T).T, axis=1) - target

    hi0, si0 = _lse_init(mag_data, expected_field)
    p0 = np.array([
        hi0[0], hi0[1], hi0[2],
        si0[0,0], si0[1,1], si0[2,2],
        si0[0,1], si0[0,2], si0[1,2]
    ])

    result = least_squares(residuals, p0, args=(mag_data, expected_field),
                           method='lm', max_nfev=max_iter * 9)

    hi = result.x[:3]
    sp = result.x[3:9]
    si = np.array([[sp[0],sp[3],sp[4]],[sp[3],sp[1],sp[5]],[sp[4],sp[5],sp[2]]])

    ev = np.linalg.eigvals(si)
    if np.min(ev) <= 0:
        si += (1e-6 - np.min(ev) + 1e-6) * np.eye(3)

    calibrated = (si @ (mag_data - hi).T).T
    radii = np.linalg.norm(calibrated, axis=1)

    quality = {
        'mean_radius': float(np.mean(radii)),
        'std_radius': float(np.std(radii)),
        'relative_std': float(np.std(radii) / np.mean(radii)) if np.mean(radii) > 0 else 999,
        'n_samples': len(mag_data),
    }

    return hi, si, quality, calibrated


def emfi_pct(data, ef, thresholds=[1, 2, 5]):
    """Percentage of points within ±threshold% of EMFI."""
    mags = np.linalg.norm(data, axis=1)
    result = {}
    for t in thresholds:
        lo, hi = ef * (1 - t/100), ef * (1 + t/100)
        result[t] = float(np.sum((mags >= lo) & (mags <= hi)) / len(mags) * 100)
    return result


# ---------------------------------------------------------------------------
# File I/O
# ---------------------------------------------------------------------------
def save_calibration(hi, si, quality, raw_pct, cal_pct, ef, path, csv_name):
    with open(path, 'w') as f:
        f.write("# Magnetometer Calibration Parameters (Navigator)\n")
        f.write("# Generated by get_nav_mag_cal.py\n")
        f.write(f"# Method: LM\n")
        f.write(f"# Sensor: Navigator\n")
        f.write(f"# Units: µT\n")
        f.write(f"# Raw data: {csv_name}\n")
        f.write(f"# Samples: {quality['n_samples']}\n")
        f.write(f"# Mean radius: {quality['mean_radius']:.6f} µT\n")
        f.write(f"# Std radius: {quality['std_radius']:.6f} µT\n")
        f.write(f"# Relative std: {quality['relative_std']:.4f}\n")
        f.write(f"# Expected field strength: {ef:.6f} µT\n")
        f.write("#\n")
        f.write("# EMFI Percentage Analysis:\n")
        for t in sorted(raw_pct.keys()):
            f.write(f"# Within ±{t}% of EMFI: Raw {raw_pct[t]:.2f}% → Calibrated {cal_pct.get(t,0):.2f}%\n")
        f.write("\n")
        f.write(f"b = {hi[0]:.12f},{hi[1]:.12f},{hi[2]:.12f}\n")
        f.write(f"# Note: Hard iron values in µT\n")
        f.write("A = " + ",".join(f"{x:.12f}" for x in si.flatten()) + "\n")


# ---------------------------------------------------------------------------
# Diagnostic plot (3 columns × 1 row)
# ---------------------------------------------------------------------------
def plot_diagnostics(raw_data, calibrated, ef, units, output_path):
    """Generate 3-panel diagnostic: raw sphere, cal sphere, error distribution."""
    fig = plt.figure(figsize=(18, 6))

    # Reference sphere
    theta = np.linspace(0, np.pi, 30)
    phi = np.linspace(0, 2*np.pi, 30)
    theta, phi = np.meshgrid(theta, phi)
    sx = ef * np.sin(theta) * np.cos(phi)
    sy = ef * np.sin(theta) * np.sin(phi)
    sz = ef * np.cos(theta)

    views = [(30, 45)]  # single view angle

    # Panel 1: Raw data
    ax1 = fig.add_subplot(131, projection='3d')
    ax1.scatter(raw_data[:,0], raw_data[:,1], raw_data[:,2],
                c=np.linalg.norm(raw_data, axis=1), cmap='viridis', s=1, alpha=0.6)
    ax1.plot_surface(sx, sy, sz, color='blue', alpha=0.05)
    ax1.plot_wireframe(sx, sy, sz, color='blue', alpha=0.15, linewidth=0.3)
    ax1.set_xlabel(f'X ({units})')
    ax1.set_ylabel(f'Y ({units})')
    ax1.set_zlabel(f'Z ({units})')
    ax1.set_title('Raw Data vs EMFI Sphere')
    ax1.set_box_aspect([1,1,1])
    ax1.view_init(elev=30, azim=45)

    # Panel 2: Calibrated data
    ax2 = fig.add_subplot(132, projection='3d')
    ax2.scatter(calibrated[:,0], calibrated[:,1], calibrated[:,2],
                c=np.linalg.norm(calibrated, axis=1), cmap='viridis', s=1, alpha=0.6)
    ax2.plot_surface(sx, sy, sz, color='blue', alpha=0.05)
    ax2.plot_wireframe(sx, sy, sz, color='blue', alpha=0.15, linewidth=0.3)
    ax2.set_xlabel(f'X ({units})')
    ax2.set_ylabel(f'Y ({units})')
    ax2.set_zlabel(f'Z ({units})')
    ax2.set_title('LM Calibrated vs EMFI Sphere')
    ax2.set_box_aspect([1,1,1])
    ax2.view_init(elev=30, azim=45)

    # Panel 3: Error distribution
    ax3 = fig.add_subplot(133)
    raw_mags = np.linalg.norm(raw_data, axis=1)
    cal_mags = np.linalg.norm(calibrated, axis=1)
    raw_err = (raw_mags - ef) / ef * 100
    cal_err = (cal_mags - ef) / ef * 100

    ax3.hist(raw_err, bins=50, alpha=0.5, color='red',
             label=f'Raw (µ={np.mean(raw_err):.2f}%, σ={np.std(raw_err):.2f}%)')
    ax3.hist(cal_err, bins=50, alpha=0.5, color='green',
             label=f'LM Cal (µ={np.mean(cal_err):.2f}%, σ={np.std(cal_err):.2f}%)')
    ax3.axvline(0, color='blue', linestyle='--', linewidth=2, label='Zero Error')
    ax3.set_xlabel('Magnitude Error (% of EMFI)')
    ax3.set_ylabel('Count')
    ax3.set_title('EMFI Error Distribution')
    ax3.legend()
    ax3.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(output_path, dpi=200, bbox_inches='tight')
    plt.close()
    print(f"Saved: {output_path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description='Navigator Magnetometer Calibration (LM)')
    parser.add_argument('csv_file', help='CSV from sample_navigator')
    parser.add_argument('--emfi', type=float, default=51.272, help='Expected EMFI in µT (default: 51.272, Boston)')
    parser.add_argument('--output', '-o', help='Output directory (default: current directory)')
    parser.add_argument('--verbose', '-v', action='store_true')
    args = parser.parse_args()

    csv_path = Path(args.csv_file)
    if not csv_path.exists():
        print(f"Error: {csv_path} not found")
        sys.exit(1)

    output_dir = Path(args.output) if args.output else Path('.')
    output_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(csv_path)
    df.columns = df.columns.str.strip()

    # Navigator mag columns (µT)
    mag_cols = ['nav_mag_x_ut', 'nav_mag_y_ut', 'nav_mag_z_ut']
    for col in mag_cols:
        if col not in df.columns:
            print(f"Error: column '{col}' not found")
            print(f"Available: {list(df.columns)}")
            sys.exit(1)

    mag_data = df[mag_cols].dropna().to_numpy()
    ef = args.emfi

    print(f"Navigator Magnetometer Calibration (LM)")
    print(f"Input: {csv_path}")
    print(f"Samples: {len(mag_data)}")
    print(f"EMFI: {ef:.3f} µT")

    hi, si, quality, calibrated = calibrate_lm(mag_data, ef)

    raw_pct = emfi_pct(mag_data, ef)
    cal_pct = emfi_pct(calibrated, ef)

    # Save calibration file
    dat_path = output_dir / 'mag_cal_nav.dat'
    save_calibration(hi, si, quality, raw_pct, cal_pct, ef, dat_path, csv_path.name)
    print(f"Saved: {dat_path}")

    # Save diagnostic plot
    plot_path = output_dir / 'mag_cal_nav_diagnostics.png'
    plot_diagnostics(mag_data, calibrated, ef, 'µT', plot_path)

    # Print summary
    grade = ('EXCELLENT' if quality['relative_std'] < 0.05 else
             'GOOD' if quality['relative_std'] < 0.10 else
             'FAIR' if quality['relative_std'] < 0.15 else 'POOR')

    print(f"\nCalibration: {grade}")
    print(f"  Hard Iron: [{hi[0]:.4f}, {hi[1]:.4f}, {hi[2]:.4f}] µT")
    print(f"  Mean |B|:  {quality['mean_radius']:.4f} µT")
    print(f"  Rel Std:   {quality['relative_std']*100:.2f}%")
    print(f"  EMFI compliance:")
    for t in sorted(raw_pct.keys()):
        print(f"    ±{t}%: {raw_pct[t]:.1f}% → {cal_pct[t]:.1f}%")


if __name__ == '__main__':
    main()
